eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: films
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/films/**, /api/v1/actors/**, /api/v1/genres/**
          filters:
            - AuthenticationFilter
        - id: payments
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthenticationFilter
        - id: screenings
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/screenings/**, /api/v1/seats/**, /api/v1/cinemas/**
          filters:
            - AuthenticationFilter
        - id: currencies
          uri: http://localhost:8000
          predicates:
              - Path=/api/v1/codes/**
          filters:
            - AuthenticationFilter
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**
          filters:
            - AuthenticationFilter
        - id: emailSender
          uri: http://localhost:8022
          predicates:
            - Path=/api/v1/send/**
          filters:
            - AuthenticationFilter
        - id: tickets
          uri: http://localhost:9010
          predicates:
            - Path=/api/v1/book/**
          filters:
            - AuthenticationFilter
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
